name: signal-cli-gael
version: "v0.13.16"
base: core24
summary: signal-cli
description: |
  signal-cli is a commandline interface for the Signal messenger. It supports registering, verifying, sending and receiving messages. signal-cli uses a patched libsignal-service-java, extracted from the Signal-Android source code. For registering you need a phone number where you can receive SMS or incoming calls.

  signal-cli is primarily intended to be used on servers to notify admins of important events. For this use-case, it has a daemon mode with D-BUS interface (man page) and JSON-RPC interface (documentation). For the JSON-RPC interface there's also a simple example client, written in Rust.

grade: stable 
confinement: strict

platforms:
  amd64:

license: "GPL-3.0-or-later"

apps:
  signal-cli-receive:
    command: signal-cli-receive.sh
    daemon: simple
    install-mode: disable
    timer: 00:00-24:00/6
    environment:
      XDG_DATA_HOME: $SNAP_DATA
      XDG_RUNTIME_DIR: $SNAP_DATA
    plugs:
    - network

  signal-cli-from-stdin:
    command: signal-cli-from-stdin.sh
    environment:
      XDG_DATA_HOME: $SNAP_DATA
      XDG_RUNTIME_DIR: $SNAP_DATA
    plugs:
    - network

  signal-cli:
    command: signal-cli
    environment:
      XDG_DATA_HOME: $SNAP_DATA
      XDG_RUNTIME_DIR: $SNAP_DATA
    plugs:
    - network

parts:
  scripted_build:
    plugin: dump
    source: snap/local/target

  launchers:
    plugin: dump
    source: snap/local/launchers
